Social packages test
gewaer/gewaer-api pull request #51
Opened 2020-09-30 18:49 UTC by rwhite27

New features:

- Create and Delete Messages
- Create, Edit and Delete comments from messages

2020-09-30 20:17 UTC, FredPeal commented
@rwhite27 the test is not success

2020-10-01 13:24 UTC, kaioken requested changes

2020-10-01 13:24 UTC, kaioken commented on api/controllers/FeedsController.php
> +            'conditions' => 'uuid = :uuid:',
@rwhite27 look it up as a relationship could also be a solution , but do change the comments to english

2020-10-01 13:41 UTC, rwhite27 commented on api/controllers/FeedsController.php
> +            'conditions' => 'uuid = :uuid:',
done. Now lead's channel is fetched via the relationship between leads and channels.

2020-10-05 17:15 UTC, FredPeal commented on phinx-social.php
> +            'host' => getenv('DATA_API_SOCIAL_MYSQL_HOST'),
add this new variables to .env.example

2020-10-06 13:41 UTC, merged