Add friendlyName on createChat and add user photo and name on chat us…
gewaer/gewaer-api pull request #59
Opened 2020-10-13 20:19 UTC by rwhite27

…er creation

2020-10-13 20:25 UTC, kaioken approved these changes

2020-10-13 20:33 UTC, jesusantguerrero requested changes
In both cases we need to update the data if the channel or user already exist.

2020-10-13 20:33 UTC, jesusantguerrero commented on library/Services/Chat.php
>              $channel = $this->twilio->chat->v2->services($this->chatServiceSid)
If we find the channel here we'll need to update the friendlyname to support lead updates

2020-10-13 20:33 UTC, jesusantguerrero commented on library/Services/Chat.php
>              $user = $this->twilio->chat->v2->services($this->chatServiceSid)
If the user is already created update its data. to support profile changes and name.

2020-10-14 14:12 UTC, jesusantguerrero approved these changes

2020-10-14 14:16 UTC, merged