Add messages mapper and default comments per message
gewaer/gewaer-api pull request #64
Opened 2020-10-19 20:16 UTC by rwhite27

2020-10-19 20:23 UTC, kaioken requested changes

2020-10-19 20:23 UTC, kaioken commented on library/Mapper/MessagesMapper.php
> +            $messageDto->comments[] = $comments;
@rwhite27 why not just do $messageDto->comments = $messageComments->toArray(); withtou the foreach?

2020-10-20 15:35 UTC, kaioken approved these changes

2020-10-20 18:33 UTC, jesusantguerrero approved these changes

2020-10-20 18:36 UTC, merged